### PR TITLE
Use Script-based signing for messages

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by jtimon** [comment]
ut ACK.

**Comment by luke-jr** [comment]
Would be nice to support HD derivation somehow to avoid signatures leaking the public key. Is this feasible?

**Comment by jtimon** [comment]
This is also a good excuse to PR script/generic.hpp to Bitcoin Core...

**Comment by gmaxwell** [comment]
Soft-forks make this fail open.

**Comment by jtimon** [comment]
> Soft-forks make this fail open.

Can you elaborate on that? I don't think I understand.

**Comment by gmaxwell** [comment]
A soft fork adds a new script feature.  I create a new address that uses it and publish that.

You accept my pubkey.

In the future someone gives you an invalid signature with my key and you verify it with old software, the signature will pass without warning.

**Comment by jtimon** [comment]
Thanks. Mhmm, that seems intrinsically unsolvable...I guess you mean to solve it using versions (maybe the validation flags?) in the signed messages or something of the sort.

**Comment by gmaxwell** [comment]
Yes.

**Comment by sipa** [comment]
@gmaxwell We could restrict future changes to message signing to identifiable things (specifically: NOP opcodes and segwit script versions).

**Comment by maaku** [comment]
Well message validation is not consensus code. It's acceptable for the signature validator to throw an exception if unrecognized soft-fork features are used. The API gets a little ugly as the result becomes a triple-valued boolean of Valid/Invalid/UpgradeRequired, but I don't see how that is avoidable. The UpgradeRequired exception is thrown if an unrecognized NOP or segwit script version is used.

**Comment by jtimon** [comment]
utACK ddf13c5b48a34125681a313f61306f1b13cea39e

I like the idea of the upgrade-required-to-verify-this-scriptSig exception.
Perhaps we want just want a script version at the beginning of the script ala segwit2 (meaning the newer softfork version)?
Then we could show a warning if the verification passes (but still reject the message if it fails even with the old known rules).

**Comment by sipa** [comment]
@maaku No need for an exception. Just evaluate once with SCRIPT_VERIFY_DISCOURAGE_UPGRADABLE_NOPS and once without. If the result differs, return UpgradeRequired.

**Comment by jtimon** [comment]
ack @sipa's outlined final design.

**Comment by jtimon** [comment]
Perhaps this can be replaced by a PR to https://github.com/ElementsProject/elements/commits/elements-0.13.1 or just be closed?

**Comment by jtimon** [comment]
Closing all alpha open PRs for clarity. We can always reopen them if this is a mistake.

**Pull request closed without merging**
