### PR TITLE
[0.17] QA: Use resgtest2 chain instead of regtest for rpc tests

### PR DESCRIPTION
**Pull request by jtimon**
Backport of https://github.com/bitcoin/bitcoin/pull/8994

The tests seem to pass with:

```
python3 ./test/functional/test_runner.py -j4 --extended
```

Let's please try to keep all general review things on https://github.com/bitcoin/bitcoin/pull/8994 and elements-specific things here.

Dependencies:

- [x] [0.17] Don't edit Chainparams after initialization #427
- [x] [0.17] Test: Fix example_test.py #434

### CODE REVIEW

**Comment by jtimon** [comment]
Now the -extended tests seem to pass

**Comment by instagibbs** [comment]
The motivation for this is to test the testchains feature?

**Comment by jtimon** [comment]
It's to be able to create custom testchains like we do in elements-0.14, it also adapts the tests to run with -chain=regtest2, which implies a different genesis block which doesn't satisfy pow.
It also makes customizable some chainparams we currently customize in elements-0.14.

**Comment by stevenroose** [comment]
Do you want to merge this right away, or wait for final feedback of upstream? LGTM at least!

**Comment by jtimon** [comment]
Actually that's a good question, while feedback is coming fast in bitcoin core, it seems sensible to keep them as similar as possible and wait here. On the other hand, the bitcoin PR could take too long to get merged or not even get merged, so we don't want to wait forever. So, not sure.

**Comment by instagibbs** [comment]
Perhaps we should just set a deadline and merge by then? This is kind of blocking follow-up PRs.

**Comment by stevenroose** [comment]
ACK if we want to merge it now!

**Pull request merged**
