### PR TITLE
bad-txns-in-belowout -> bad-txns-in-ne-out

### PR DESCRIPTION
**Pull request by kallewoof**
The error message indicates that the outputs exceed the inputs. In reality, at least for blinded transactions, the error will also appear if the in exceeds the out, i.e. this error appears for all transactions where inputs do not sum up to outputs.

### CODE REVIEW

**Comment by instagibbs** [comment]
ACK

**Comment by instagibbs** [comment]
could you change p2p-fullblockstest.py error to match?

**Comment by kallewoof** [comment]
Yep, will address in the morning.

**Comment by kallewoof** [comment]
@instagibbs Done.

**Comment by jtimon** [comment]
utACK 813f562eeec241e7a9b4c5597b29e29731428f18

**Comment by instagibbs** [comment]
utACK

**Pull request merged**
