### PR TITLE
Support locked Bitcoin wallets in sidechain manipulation script

### PR DESCRIPTION
**Pull request by droark**
As is, the sidechain manipulation script chokes during the "send-to-sidechain" step if the wallet is locked. I've added rudimentary support for unlocking wallets. There are a couple of notes.

- As written, the user must manually edit the password. I'd prefer to make the password an optional CL parameter. If this is preferential, let me know and I'll go back and edit all files as necessary.
- While it's doubtful that the script will encounter a pre-0.9 BC Core, the code compensates for the pre-0.9 "wallet already unlocked" error (RPC_WALLET_ALREADY_UNLOCKED) if it's encountered. Any other error kills the script. It's a bit crude but it should work.
- Is 1000 the default unlock time? I'm happy to change it as necessary. (Perhaps it would be best to use 10 instead?)

Thanks.

### CODE REVIEW

**Comment by droark** [comment]
*taps mic* Hello?

**Comment by TheBlueMatt** [comment]
Sure, I dont see why not.

**Comment by gwillen** [comment]
Excellent. @droark, want to make it a commandline arg instead of hardcoded, and then we'll merge it? Thanks!

**Comment by droark** [comment]
Thanks. I have code and am working on testing. Of course, things have gone a bit sideways (tried to rebase and may have borked the history), so I may end up closing this and trying again.

Also, I ended up following the alpha-README directions and compiled/installed the latest secp256k1. I'm getting the following error. Any ideas? This was before and after I tried a rebase of the alpha code. I'm assuming this has to do with some recent secp256k1 commits I saw and means I'll need to rewind to a few months ago?

```
droark@ubuntu:~/Projects/PersonalGitRepo/ElementsProject/elements/contrib$ python sidechain-manipulation.py send-to-sidechain 2Mthy8EMKtSXWQmDTKd1Bf676ZJJFkr6VGP 0.1
[libsecp256k1] illegal argument: *outputlen >= ((flags & SECP256K1_FLAGS_BIT_COMPRESSION) ? 33 : 65)
Aborted (core dumped)
```

**Comment by gwillen** [comment]
@droark Indeed, take a look at #59 -- apparently an API changed in the meantime. I don't yet know where exactly you need to rewind to, but that is the solution.

**Comment by droark** [comment]
Thanks. I got everything rewound properly and can proceed. I'll close this one out and open a new one soon. (Got distracted by life. Blargh.)

**Comment by gwillen** [comment]
Not a problem @droark, thanks for still working on this after we let it stall for 3 months. Much appreciated!

**Comment by droark** [comment]
Closing this out in favor of a less borked branch and with much more complete code.

**Pull request closed without merging**
