### PR TITLE
[upstream #10627] fixed listunspent rpc convert parameter

### PR DESCRIPTION
**Pull request by tnakagawa**

### CODE REVIEW

**Comment by instagibbs** [comment]
This appears to be a bug upstream in Core. Mind opening another PR there too to make sure we don't need this next rebase?

**Comment by jtimon** [comment]
Perhaps also add { "listunspent", 4, "asset" } (only here, not upstream the asset field to bitcoin core, obviously).
Apart from that, utACK

**Comment by tnakagawa** [comment]
'VRPCConvertParams' can only set parameters other than strings?

**Comment by instagibbs** [comment]
Yes only for no strings.

**Comment by jtimon** [comment]
Oh, right, my bad. Should correct #185 ...
re-utACK

**Review by apoelstra — APPROVED** [review]
ACK 789cb198eac580a8c5bb42da65cd6551e8707dce

**Pull request merged**
