### PR TITLE
2WP: -mainchainrpccookiefile defaults to regtest/.cookie for all chains

### PR DESCRIPTION
**Pull request by jtimon**
Decouple GetMainchainAuthCookieFile() from the selected chain's datadir.

### CODE REVIEW

**Comment by instagibbs** [comment]
how do you see this scaling when we have more networks built in?

**Comment by jtimon** [comment]
My preferred option would be to make -mainchainrpccookiefile mandatory if you're validating pegs or simply let it at regtest.
Another option would be to introduce a default_mainchainrpccookiefile to the configurable chainparams.
Ideally support for more networks should be simply provided by configuring the custom/regtest chainparams.

**Comment by jtimon** [comment]
Rebased

**Comment by instagibbs** [comment]
request: in `pegging.py`, have one of the two elementsd use the option instead of rpcuser/password. Manually testing now.

**Comment by instagibbs** [comment]
ah hm, can't figure out how to get AuthProxy to work with cookie auth for pegging.py. Manual testing showed a related bug: https://github.com/ElementsProject/elements/pull/292

tACK, but I'd like to get some tests in too if at all possible

**Comment by jtimon** [comment]
The bitcoin node either uses has user/pass defined or it creates the cookie file.
I've changed pegging so that -mainchainrpccookiefile is tested rather than -mainchainrpcpassword and -mainchainrpcuser.
Does that make sense?

**Comment by instagibbs** [comment]
Could we test both? Spin up a second bitcoind, check that it accepts the block with a pegged transaction?

**Comment by jtimon** [comment]
Done, now each sidechain node connects to each own bitcoin node, which also connect between them.
I can squash the last 3 commits if you want.

**Comment by instagibbs** [comment]
utACK, don't mind the commits

**Pull request merged**
