### PR TITLE
Import settings from constants.py into sidechain-manipulation.py

### PR DESCRIPTION
**Pull request by TomMcCabe**
Avoids redundancies with changing the same settings in two separate files.

### CODE REVIEW

**Comment by martindale** [comment]
ACK.

**Comment by gwillen** [comment]
Oops, I was getting ready to merge this, but actually "secondScriptPubKey", removed from sidechain-manipulation.py is missing from constants.py. @TomMcCabe, can you fix, and double-check that nothing else is missing?

And can you please edit alpha-README.md to refer to editing config.py instead of sidechain-manipulation.py, to match the code change (and any other documentation you're aware of)?

Thanks!

(I think the reason this was not done this way to start with, was that 'fedpeg' was supposed to be a specialization of the general concept of sidechains, and so it doesn't make sense for this script to depend on something in 'fedpeg'. However, I think the removal of redundancy is more valuable than preserving that currently-theoretical separation, and we can always refactor it later.)

**Comment by TomMcCabe** [comment]
@gwillen: Fixed as requested and squashed commits.

**Comment by gwillen** [comment]
Awesome, thanks and sorry for the delay. Taking a look now.

**Comment by gwillen** [comment]
Lightly-tested ACK.

I don't know if there are conflicting views on this, but as a matter of personal preference, I tend to suggest waiting until after final review to squash (because it makes it easy for the reviewer to see what changed since the last review.)

I have rebased and will push.

**Comment by gwillen** [comment]
Heh, github still claims this can be merged, probably because I did a rebase-push without updating the code on the pullreq. But it's in! Thanks for doing this. :-)

**Pull request closed without merging**
