### PR TITLE
regtest: change network magic away from liquid v1

### PR DESCRIPTION
**Pull request by apoelstra**
We don't want connectivity issues between Liquid and custom test networks.

### CODE REVIEW

**Comment by stevenroose** [comment]
ACK e57b4c51ad2ee43897d2fcac4e7cd6b8858c674f

**Comment by apoelstra** [comment]
This change is actually pretty invasive.

* On existing regtest networks, or 0.18 networks where you try to test upgrading to 0.21, you will get silent inability to connect
* Worse(?) when starting up, you get assertion errors loading blocks from disk as the network magic appears in the disk serialization

I think we should probably revert this, even though it is regtest-only.

cc @psgreco

**Comment by apoelstra** [comment]
Or maybe we should put output a warning on startup for a couple of versions.

**Comment by apoelstra** [comment]
Also, if we keep this change, we should've done it to` LiquidV1Test` as well as regtest/custom.

**Pull request merged**
