### PR TITLE
Document -signblockscript and -fedpegscript in daemon help

### PR DESCRIPTION
**Pull request by jtimon**
Also document -validatepegin.

### CODE REVIEW

**Comment by Christewart** [comment]
May be a dumb question, but what happens to the data directory if you change `signblockscript` / `fedpegscript`? Since we are creating a new chain, does it over write everything?

**Comment by instagibbs** [comment]
@Christewart a different `signblockscript` will trigger an "incorrect genesis block" error since the block changes. We also have a change to commit to the `fedpegscript` as well, to reduce chances of losing money: https://github.com/ElementsProject/elements/pull/164

This can be bypassed by reindexing or deleting the folder.

**Comment by instagibbs** [comment]
@jtimon you're missing `DEFAULT_VALIDATE_PEGIN` definition.

**Comment by jtimon** [comment]
Oops, fixed, thanks.

**Comment by instagibbs** [comment]
compile/utACK

**Pull request merged**
