### PR TITLE
HF: Move block.proof.challenge to Consensus::Params::signblockscript

### PR DESCRIPTION
**Pull request by jtimon**
Since the scriptPubKey for signing blocks never changes, there's no
point in repeating it with every block header.

Closed https://github.com/ElementsProject/elements/pull/189 by accident, it seems restoring the branch doesn't make it, so I opened this one instead.

Dependencies:

- [x] RPC: Stop providing useless fake pow data #344 [e14-cleanup-pow]
- [x] NO-HF: Move block.proof.challenge to Consensus::Params::signblockscript #386 [e14-blocksign-no-hf]

### CODE REVIEW

**Comment by jtimon** [comment]
Fixed bug, checking hashPrevBlock.IsNull() instead of proof.IsNull() in CBlockHeader::IsNull().
Perhaps hashMerkleRoot.IsNull() would be more appropriate?
Thanks @instagibbs for finding the bug.

Probably a good next simplification step is to remove the Proof class, now more clearly redundant.

**Comment by instagibbs** [comment]
utACK https://github.com/ElementsProject/elements/pull/313/commits/fe713a696a087665099aa3edc747ef6ae5b96fce

**Comment by jtimon** [comment]
Rebased. Separating https://github.com/ElementsProject/elements/pull/386 out of this.

**Comment by jtimon** [comment]
needs rebase

**Comment by instagibbs** [comment]
Needs port to master branch at some point. Will be undertaken for https://github.com/ElementsProject/elements/issues/534 . Closing.

**Pull request closed without merging**
