### PR TITLE
Scripts and tools: Add Docker and docker-compose files

### PR DESCRIPTION
**Pull request by stakauskas**
Ability to build and run Elements from Docker. Builds docker image and starts with docker-compose, easy to modify parameters, add configuration files and scale containers.

### CODE REVIEW

**Comment by jtimon** [comment]
Concept ACK
Perhaps this can be upstreamed to https://github.com/bitcoin/bitcoin ?
We will likely get faster and more review and testing there, and then do the same thing here.

**Comment by stakauskas** [comment]
Good point @jtimon - will do that.

**Comment by Deadlyelder** [comment]
Hi,

Unsuccessful execution on the command `docker-compose -p elements up -d`.
Error thrown on the keyserver timing out for the given key.

A manual check does not find the key either:
```bash
gpg --status-fd 1 --keyserver ha.pool.sks-keyservers.net \
--recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4

[GNUPG:] FAILURE recv-keys 167805060
gpg: keyserver receive failed: Operation timed out```

Regards.

**Comment by jtimon** [comment]
I'm sorry, what's the status for this?

**Comment by instagibbs** [comment]
Closing due to lack of activity and the closed upstream PR.

Please re-open a rebased version on master branch if you're still interested in completing this.

**Pull request closed without merging**
