### PR TITLE
Add signrawtransactionwithkey test with amount commitments

### PR DESCRIPTION
**Pull request by k-matsuzawa**
- This test assumes a fix for #904. Before correction, the test will result in an error.
- I splited the node network in rpc_signrawtransaction.py to do this test.
- For now, I have only created one test case. Are there any other test cases that should be added?

### CODE REVIEW

**Comment by wtogami** [comment]
(Not a code review)

Typo in your branch name and PR title.

**Comment by k-matsuzawa** [comment]
Sorry, fix RP title. Please forgive the mistake of the branch name.
Thanks!

**Comment by gwillen** [comment]
Thank you very much! I reviewed the test and it looks good (I haven't tried running it yet.) This will be very helpful to verify the fix, once we get #904 in.

**Comment by k-matsuzawa** [comment]
Rebased.

**Comment by stevenroose** [comment]
ACK fbdb9f371

**Comment by stevenroose** [comment]
Thanks!

**Pull request merged**
