### PR TITLE
Add link to RPC docs in readme

### PR DESCRIPTION
**Pull request by FrancisPouliot**
The RPC docs are a great way to understand the difference between Bitcoin and Elements. 

It should be highlighted along with the other differences from Bitcoin Core in the same section.

Alternatively, add them to Elements/Doc

### CODE REVIEW

**Comment by instagibbs** [comment]
yeah looks like we lost the docs in their modern place: https://github.com/ElementsProject/elementsbp-api-reference/ see deprecated message. We need to update the docs, maybe starting with elements-specific calls.

**Comment by stevenroose** [comment]
Could you perhaps update this PR by using this link to the documentation: https://elementsproject.org/en/doc/

**Comment by FrancisPouliot** [comment]
@stevenroose hadn't seen that actually. Thanks for sharing! Would be nice if you also added the elements-specific changes perhaps by making the RPC calls bold or something

**Comment by FrancisPouliot** [comment]
Done

**Comment by stevenroose** [comment]
Hmm just notice that the README still says "additional RPC ..." while the linked docs show all.. Perhaps change that accordingly?

**Pull request merged**
