### PR TITLE
Fix parsing of amount commitments from prevtxs in signrawtrasnactionwithkey

### PR DESCRIPTION
**Pull request by gwillen**

### CODE REVIEW

**Comment by gwillen** [comment]
Travis failure is a consequence of the issue fixed by #905, unrelated to this PR.

**Comment by stevenroose** [comment]
Can you rebase now that CI passes again? :)

**Comment by gwillen** [comment]
Rebased.

**Comment by gwillen** [comment]
@stevenroose Can you kick CI to retry (or let me know how?) There are two failures, one is just a spurious timeout, the other one is in an unrelated test and might also be a timeout of some sort (or I'm not sure what's going on with it.)

**Comment by stevenroose** [comment]
ack a4045d21e

**Pull request merged**
