### PR TITLE
adding elip001

### PR DESCRIPTION
**Pull request by acrual**
This is ELIP-001 laying out the instructions for ELements Improvement Proposals going forward

### CODE REVIEW

**Comment by delta1** [comment]
ack 0e60ee5

**Comment by apoelstra** [comment]
Thanks! Could you PR this to https://github.com/ElementsProject/ELIPs/?

You can have ELIP number 2 and say that this document supercedes the existing ELIP1 (which was just copied from the BIPs repo) if you like.

**Comment by acrual** [comment]
Hey Andrew, thanks for this, since I'm a very infrequent github user, let
me pause and remember the how to and I'll get it done asap,

**Comment by andreabonel** [comment]
Replaced by https://github.com/ElementsProject/ELIPs/pull/3

**Pull request closed without merging**
