### PR TITLE
Adding script to generate element blocks

### PR DESCRIPTION
**Pull request by Christewart**
Adding script to generate elements blocks in 1 of 1 regtest mode. Usage: 

```
$ python generate_element_blocks.py --num=100 --datadir=$BETADATADIR
```

### CODE REVIEW

**Comment by instagibbs** [comment]
Could you make a new folder `elements-devtools` in `contrib` and stick it in there?

Also, try to kill off some of the extra whitespace that are on the ends of lines.

**Comment by jtimon** [comment]
utACK 5eac851

**Comment by jtimon** [comment]
Maybe add at the beginning:
```
#!/usr/bin/env python3

"""
Some documentation for the script
"""

```

**Comment by jtimon** [comment]
Further improvements can be done in different PRs, I think. Merging.
Thanks!

**Pull request merged**
