### PR TITLE
Create fedpeg-README.md

### PR DESCRIPTION
**Pull request by TomMcCabe**
Add a detailed build instructions for constructing new fedpeg/sidechain.

### CODE REVIEW

**Comment by martindale** [comment]
+1, this is great work!  Strong ACK from me.  Thanks for submitting this – will support merging sooner rather than later, as something is better than nothing.  We can always iterate and improve on documentation.

**Comment by Christewart** [comment]
tACK

**Comment by TomMcCabe** [comment]
Revised and improved. Tested this walkthrough with 1-of-1 (local) and 2-of-2 (separate nodes). Also squashed the commits.

**Comment by gwillen** [comment]
Thanks for your work on this, @TomMcCabe . This has been sitting around for quite awhile, I'm going to make an effort to get it tested again and then merged. Please feel free to bother me if you don't hear back for awhile.

**Comment by TomMcCabe** [comment]
@gwillen This is me bothering you :stuck_out_tongue:

**Comment by instagibbs** [comment]
squash please :) 

ACK on bugging

**Comment by gwillen** [comment]
I'm going to go ahead and merge this because it's been sitting around too long, it's too useful not to have, and since it's documentation I'm not to concerned about getting it any more testing.

**Comment by gwillen** [comment]
Done, thanks again for writing this (and being so patient about it!)

**Pull request closed without merging**
