### PR TITLE
build(deps): update secp256k1-zkp

### PR DESCRIPTION
**Pull request by delta1**
Updates secp256k1 sources to BlockstreamResearch/secp256k1-zkp@533571d6cf6cc03f9bd3ce54e28765b16d59e4cb  

CI on master branch is still missing backports from upstream. I have tested this with `make check` as well as running test_runner.py successfully (after cherry-picking [these two commits](https://github.com/bitcoin/bitcoin/pull/23716/commits) from upstream)

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
ACK 12b11e36926d4e236db502e55de1516a6cbe2611

I reproduced the same two commits. Not sure about the CI failure.

**Comment by delta1** [comment]
Thanks @jonasnick - the CI is still generally broken waiting for some backports from upstream to make it to master  (I think they are already on the 22.x branch)

**Comment by psgreco** [comment]
Running all the tests on top of 22.1.1 to confirm, but there's a linter test that's failing in this PR
```
File "src/secp256k1/contrib/musig2-vectors.py" is missing expected shebang #!/usr/bin/env python3
ERROR: There were 1 failed tests in the lint-files.py lint test. Please resolve the above errors.
```

**Comment by psgreco** [comment]
Ran all the tests on top of 22.1.1 as a part of my test PR here https://github.com/ElementsProject/elements/pull/1161. It all passed except for the linter. The shebang mentioned in the failure needs to be fixed as a part of secp, so the linter doesn't fail checking the upstream references (as seen in the test PR)

**Comment by jonasnick** [comment]
What's the problem with the existing shebang in musig2-vectors.py?

```
#!/usr/bin/env python
```

**Comment by psgreco** [comment]
> What's the problem with the existing shebang in musig2-vectors.py?
> 
> ```
> #!/usr/bin/env python
> ```

Bitcoin linter expects it to be python3, not python, which could be either 2 or 3 (yes, there are still some python2 out there).

You can see the error message here
https://github.com/ElementsProject/elements/pull/1248/checks?check_run_id=15132500914

**Comment by jonasnick** [comment]
Hm seems like a bug in Core, since python2 has been end of life for more than 3 and a half years. Opened a PR to change it nonetheless.

https://github.com/BlockstreamResearch/secp256k1-zkp/pull/255

**Comment by delta1** [comment]
updated to BlockstreamResearch/secp256k1-zkp@bfeae121fb  

@pgreco should rebase so it's only 1 set of commits?

**Comment by delta1** [comment]
> updated to [BlockstreamResearch/secp256k1-zkp@bfeae121fb](https://github.com/BlockstreamResearch/secp256k1-zkp/commit/bfeae121fb) to include the latest from upstream with [BlockstreamResearch/secp256k1-zkp#255](https://github.com/BlockstreamResearch/secp256k1-zkp/pull/255) 

redid the subtree pull so it's only 1 set of commits

**Comment by delta1** [comment]
updated to latest master blockstreamresearch/secp256k1-zkp@b911b3cbd5  

tested with `make check` and `test/functional/test_runner.py`

**Comment by delta1** [comment]
Added a fix for the Windows build failure

**Comment by psgreco** [comment]
@jonasnick can you re-ack? windows builds are working again, I'll merge after you ack

**Review by jonasnick — COMMENTED** [review]
The subtree update itself looks good.

Note that Core solves the Windows build failure slightly differently (using CORE_CPPFLAGS):

https://github.com/bitcoin/bitcoin/pull/28093/commits/5080c9c25f44ae9d16a69d41f0da1d1e06483bf7#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810

Note that there are a bunch of backwards-compatible changes and deprecations in this version of libsecp (see [CHANGELOG](https://github.com/BlockstreamResearch/secp256k1-zkp/blob/master/CHANGELOG.md)) that Bitcoin Core has addressed, in particular:
https://github.com/bitcoin/bitcoin/pull/26691/commits/3bfca788b0dae879bfc745cc52c2cb6edc49fd70
https://github.com/bitcoin/bitcoin/pull/26691/commits/4462cb04986d77eddcfc6e8f75e04dc278a8147a

Since these changes are not strictly necessary, I'm happy to
ACK 048984aca4796d288772d8ab781c13ced0c2fade

Bitcoin Core has also excluded libsecp from the linter:
https://github.com/bitcoin/bitcoin/pull/27445/commits

List of Bitcoin Core PRs updating libsecp:

https://github.com/bitcoin/bitcoin/pull/26691
https://github.com/bitcoin/bitcoin/pull/27230
https://github.com/bitcoin/bitcoin/pull/27445
https://github.com/bitcoin/bitcoin/pull/28093

**Comment by psgreco** [comment]
Yes, most of those fixes are gonna end up coming anyway from the backports, so the surgical build fix is good enough for now

**Pull request merged**
