### PR TITLE
Updated README links to point to new elementsproject.org content.

### PR DESCRIPTION
**Pull request by wintercooled**
Changed links to point to new website content and removed references to old pages.

Includes some minor text changes to the intro and summary to remove suggestion its intended primary use is as a Bitcoin testbed.

Removed links to Schnorr, SW as these do not have pages on the new site (can add if needed).

### CODE REVIEW

**Comment by stevenroose** [comment]
SW I understand, but why was Schnorr also omitted from the new website? Just curious.

**Comment by wintercooled** [comment]
@stevenroose - It was listed on this page as being current but that was not the case: https://github.com/ElementsProject/elementsproject.org/blob/master/source/elements/index.md so I just removed it. Perhaps too hasty of me. So...using this as the as the source: https://github.com/ElementsProject/elementsproject.org/blob/master/source/elements/schnorr-signatures/index.md

I will raise a PR on the new site and add a link to it here for review. 

If that's fine I'll change this PR (440) to include a link to it. That sound ok?

Cheers, Matt.

**Comment by wintercooled** [comment]
@stevenroose the PR to create the content is here for review:

https://github.com/ElementsProject/elementsproject.github.io/pull/19

If that is ok I will merge that and amend this PR (440) to point to it as a 'Research phase' feature.

**Comment by jtimon** [comment]
Afaik we had schnorr for elements alpha but we don't have it for elements-0.14.1 anymore. Perhaps we can still point to the alpha code for that.

**Comment by stevenroose** [comment]
Oh, oops. Considered we still had an opcode for it. My bad.

**Comment by wintercooled** [comment]
so @jtimon , @stevenroose  - are you happy that I add the page to elementsproject.org as per the PR here: https://github.com/ElementsProject/elementsproject.github.io/pull/19

Basically - mentions Schnorr as 'research phase' and gives details as per the investigation done by Patrick Strateman. 

@jtimon - I can add a link to the alpha code if you like? What would I link to and what is Alpha for now? I thought it was defunct?

**Comment by stevenroose** [comment]
Yeah alpha is no more afaik. It also seems that Schnorr efforts moved to Core and we'll just take it over once it lands there. But it might be worth mentioning that we used to have it.

**Comment by instagibbs** [comment]
We'll likely take on Schnorr immediately once it's merged into libsecp, in whatever form.

**Comment by wintercooled** [comment]
I've put the link to Schnorr back - it points to the Schnorr research page on .org which was all there was on the old site about it

For ref that is http://elementsproject.org/features/schnorr-signatures

This PR ok from your pov now @instagibbs @stevenroose ?

**Comment by stevenroose** [comment]
LGTM.. I'd await @instagibbs 's opinion :)

**Comment by instagibbs** [comment]
utACK, links look right

**Pull request merged**
