### PR TITLE
pubkey: fix VerifySchnorr bug which is causing testnet validation failure

### PR DESCRIPTION
**Pull request by jamesdorfman**
Fixes issue which was causing validation to fail on block 2a70e30a3b975b53a0598139f6f490ff0865a47d0028a55ddc04451270d228d0 in liquidtestnet.

This bug was introduced in the merge of https://github.com/bitcoin/bitcoin/pull/22448 in https://github.com/ElementsProject/elements/commit/09333e2aca97bc819aed26eb2835df7cf604c38d.

It is not yet clear why only a testnet block is affected by this issue, and why the production liquid chain syncs fully.

Subsequent commits in this PR contain fixes for various failing functional tests.

### CODE REVIEW

**Review by delta1 — APPROVED** [review]
utACK 47dff66

**Comment by jamesdorfman** [comment]
ACK 9368fbac1cbdeef76960cc9e2eb5955846287596.

**Comment by delta1** [comment]
ACK https://github.com/ElementsProject/elements/commit/9368fbac1cbdeef76960cc9e2eb5955846287596 - reviewed other commits

**Review by Shuhaib07 — COMMENTED** [review]
Verified

**Pull request merged**
