### PR TITLE
Add Documentation for Testing and QA

### PR DESCRIPTION
**Pull request by martindale**
This adds documentation to the `qa/` directory, giving information about how to configure and run tests.

### CODE REVIEW

**Comment by gwillen** [comment]
Is this cribbed (or partly cribbed) from the Bitcoin repo? I note that e.g. 'bitcoind' should read 'alphad' or something more generic. (I also want to check, what with mentions of Travis and such, that we actually _have_ Travis configured for Elements? I'm not sure whether we do.) And if this _is_ derived from Bitcoin documentation, and if you haven't already, make sure that e.g. the pull-tester actually works on Elements.

Also note that a lot of the Bitcoin tests are disabled in Elements because they are closely tied to Bitcoin internals and need a lot of fixing for Elements. This may not be directly relevant to this documentation but it does make the tests less useful than they appear at first.

**Comment by martindale** [comment]
Yep, this is entirely the work of @MarcoFalke as far as I can tell.  If there's a significant difference in what tests actually apply to `master` of Elements, I'd like to have those updated as part of this pull request, and ultimately included with each feature addition.  Any further guidance here would be appreciated.

Once I finish this, we can talk about enabling Travis (and perhaps even Coveralls for code coverage) to automatically run the tests we do have.  :)

**Comment by MarcoFalke** [comment]
You have duplicate content if you don't cherry-pick cc975745d585edf6ae3a9313f45da6dbdee16cf6 as well.

**Comment by jtimon** [comment]
Closing all alpha open PRs for clarity. We can always reopen them if this is a mistake.

**Pull request closed without merging**
