### PR TITLE
Fix to strip out problematic Windows %PATH%

### PR DESCRIPTION
**Pull request by trustkim**
I had problem, but solve from bitcoin repository.
So I correct here also.
Thanks :D

### CODE REVIEW

**Comment by instagibbs** [comment]
Is there a relevant Bitcoin Core PR to fix this for reference? Thanks!

**Comment by trustkim** [comment]
Here are links when I found to solve this issue:

- [https://github.com/bitcoin/bitcoin/issues/11549](url)
- [https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md#building-for-32-bit-windows](url)

your welcome

**Comment by instagibbs** [comment]
It looks like that PR was closed in favor of https://github.com/bitcoin/bitcoin/pull/11438

Does that not fix your issue? I'd rather we not drift from upstream.

**Comment by trustkim** [comment]
Hm... How can I explain about it...

I think the second link that I referred, it is result of bitcoin/bitcoin#11438.

Thanks to that PR, I can fix my issue.

**Comment by instagibbs** [comment]
ok, in that case I'd prefer that PR backported, if you'd like to submit it.

Closing for now.

**Comment by trustkim** [comment]
Ops. Sorry. I could not understand about "backport", or "PR(pull request right?)"

the PR bitcoin/bitcoin#11438 you referred was not relevant. So it can not fix my issue.

Actually in that PR, they did not refer to exactly same this issue.

So I can show you this commit: [Add new step to clean $PATH var by removing /mnt specific Window's %P…](https://github.com/bitcoin/bitcoin/pull/11437/commits/4f890ba6bc8caba5394c7a5388d7f07959ced78b)

**Comment by instagibbs** [comment]
I unfortunately have no way of testing this work :(

If it's at all possible try and get it merged upstream(In Bitcoin Core).

**Pull request closed without merging**
