### PR TITLE
Raise max P2P message size to account for larger elements dynafed header size.

### PR DESCRIPTION
**Pull request by gwillen**

### CODE REVIEW

**Comment by gwillen** [comment]
Fixes an issue we're starting to see with dynafed headers causing GETHEADERS responses to exceed the maximum P2P message size. 

This is happening because we inherited a constant from bitcoin, which hardcodes the assumption that 2000 headers will fit in a maximum-sized P2P packet and can't easily be changed:

```
/** Number of headers sent in one getheaders result. We rely on the assumption that if a peer sends
 *  less than this number, we reached its tip. Changing this value is a protocol upgrade. */
static const unsigned int MAX_HEADERS_RESULTS = 2000;
```

**Comment by gwillen** [comment]
Updated to also fix some hardcoded copies of the same constant in the python tests.

**Comment by philippem** [comment]
tACK

**Comment by psgreco** [comment]
ACK bf7f050aeb7c4f863af8ed35c0ee11f3c85991a5

**Comment by stevenroose** [comment]
Our headers are way more than 4x the size of bitcoin headers, though. It might make sense to also somehow influence how much headers the p2p logic will request in a single getdata.

But ACK on this part.

**Pull request merged**
