### PR TITLE
Add CL flag support to sidechain manipulation script

### PR DESCRIPTION
**Pull request by droark**
- Add support for command line arguments to the sidechain manipulation script. argparse requires Python 2.7 or 3.2+.
- Add support for unlocking mainchain wallet when running send-to-sidechain.
- Add various bits of help text, some of which may not be quite right.

### CODE REVIEW

**Comment by droark** [comment]
This is a more thorough (and tested) replacement for PR #44. I ended up replacing the sys.argv usage with argparse. This way, the code adds a more useful help system alongside efficient argument parsing. The one and only time that CL flags right now are to unlock Bitcoin wallets when using send-to-sidechain. I discovered that the code, when Armory is running, will use an Armory wallet. That's how I tested this.

Note that, for now, the script won't work due to libsecp256k1 API breakage. See issue #59 for details regarding where to rewind libsecp256k1 & contracthashtool in order to test this patch.

Thanks.

**Comment by droark** [comment]
Paging @gwillen. Am I on the right path? Did I go too far with the changes?

**Comment by gwillen** [comment]
No way, you didn't go too far at all, this is awesome. Let me test it out and then figure out what the process is for us to merge it. Thanks!

**Comment by droark** [comment]
Thanks, and sorry about the extra commits that just popped up! I added a commit and tried to squash it. My squash mojo just isn't right today, unfortunately. I'll clean it up one way or another.

**Comment by gwillen** [comment]
No problem. I think what you want is 'git rebase -i foo' where foo is the _parent_ of the first commit you want to squash; then replace 'pick' with 'squash' on all lines but the first: http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

And then 'git push -f [something appropriate]' to update the pullreq. (Which will nuke all inline comments on the previous commits unfortunately, but in this case there aren't any.)

**Comment by droark** [comment]
Thanks! That did the trick. I had basically done that. I didn't force the initial push, though, so something went sideways. Oh well. All's well now.

**Comment by gwillen** [comment]
Other than the comment above about the behavior in case of failure -- which I think should emulate the old behavior as much as possible if the issue is not a locked wallet -- I think this is ready to be merged.

**Comment by droark** [comment]
Oh no, it's totally fine! I'm happy to make any and all changes as needed. I'll look at everything and update in a little bit.

**Comment by droark** [comment]
@gwillen - I believe I've addressed your feedback. Forgot to run a sanity check but I'll do that right now. Anything else you'd like for me to do? Should I squash the new commit?

**Comment by gwillen** [comment]
Looks good, thanks! Go ahead and squash now that I've looked at it.

**Comment by droark** [comment]
*squash*

**Comment by gwillen** [comment]
Ok, after a bit of a battle with the commit-signing script, it is done! Thanks for your patience and thanks for your contribution!

**Comment by droark** [comment]
Thanks! I'll keep an eye out for any more contributions I can make.

**Pull request merged**
