### PR TITLE
RPC: Signblock: Support signblock info on rpc/blockchain

### PR DESCRIPTION
**Pull request by jtimon**
Bigger refactor than I initially thought.
But basically still cleaning up pow stuff we don't need, and including a few new blocksign-related fields that replace those and document them. 

Doesn't come with tests, but if it's not only rpc, then nack, please.

Dependencies:

- [x] QA: Reactivate and improve rpc_blockchain tests https://github.com/ElementsProject/elements/pull/365
~~- [ ] RPC: Stop providing useless fake pow data #366~~

### CODE REVIEW

**Comment by instagibbs** [comment]
concept ACK

**Comment by instagibbs** [comment]
Add some really basic rpc test and I'll merge

**Comment by jtimon** [comment]
It seems I found out what was happening with travis.
For some reason (I assume when calling with help) the tests expected a runtime_error instead of a JSONRPCError, see https://github.com/ElementsProject/elements/pull/344/commits/70ace1818c9c5636326407410ec7aa5070043f62

I will squash. will squash, should I squash only that commit or do more squashing?

**Comment by instagibbs** [comment]
wow, how couldn't we figure this out...

please squash into whatever you find sensible, I need to review it again

**Comment by jtimon** [comment]
Squashed only the fixup commit for now, feel free to ask for further squashing.

**Comment by instagibbs** [comment]
Apologies, could you squash the first QA one, at least, since it'll make the previous commit fail atomically?

I don't mind logic+qa changes in same commit at all.

Otherwist, utACK!

**Comment by jtimon** [comment]
I'm fine squashing both qa changes with their respective changes or even everything in one commit. At first it was just one commit for the changes and another activating and improving the tests, but after the confusing I ended up separating things more to divide and conquer and now the test re-activation is already merged.

**Pull request merged**
