### PR TITLE
Improve addrman Select() performance when buckets are nearly empty.

### PR DESCRIPTION
**Pull request by sipa**
This reduces idle CPU usage for me from 40% to 1%.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Do you have any desire to upstream this (might help for testnet/regtest sometime)

**Comment by sipa** [comment]
Long done.

**Comment by gmaxwell** [comment]
ACK

**Comment by gmaxwell** [comment]
ping

**Comment by sipa** [comment]
Rebased, and updated to the code that was merged in Bitcoin Core.

**Pull request merged**
