### PR TITLE
[elements-0.21] Release elements 0.21.0.1

### PR DESCRIPTION
**Pull request by stevenroose**
This first merges the master branch into the 0.21 release branch and then bumps the version number and updates the man pages.

### CODE REVIEW

**Comment by apoelstra** [comment]
The manpages now have a git commit ID in them.

**Comment by stevenroose** [comment]
Should be good to go now

**Comment by psgreco** [comment]
New version of the manpages looks good, UTACK 2a6dcadc838a36df3f7cd2ef39b6e3f6e6a8159d

**Comment by gwillen** [comment]
utACK 2a6dcad

**Pull request merged**
