### PR TITLE
Support supplying contract hash to issueasset RPC

### PR DESCRIPTION
**Pull request by stevenroose**
forward port of https://github.com/ElementsProject/elements/pull/993.
Closes https://github.com/ElementsProject/elements/issues/985.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you rebase this and see if that fixes CI

**Comment by stevenroose** [comment]
Done

**Comment by apoelstra** [comment]
Looks like you added an option to the RPC help but didn't add it again to the list of RPCs at the bottom of wallet/rpcwallet.cpp.

This redundancy will be removed in 22.0 but in 0.21 we just enforce consistency in CI.

**Comment by stevenroose** [comment]
I added that, sorry

**Comment by stevenroose** [comment]
Somehow CI doesn't seem to run on this one.. Does anyone understand why that is?

**Comment by apoelstra** [comment]
It looks like it ran and all the checks passed.

**Review by apoelstra — APPROVED** [review]
ACK 47d43f14ada76839c852399a31608825925fb635

**Pull request merged**
