### PR TITLE
Untested: Rpc call for per-block fee statistics

### PR DESCRIPTION
**Pull request by jtimon**
I still need to test it and squash, and there's one TODO, but review welcomed already.

### CODE REVIEW

**Comment by instagibbs** [comment]
Is there an associated issue with this?

**Comment by jtimon** [comment]
No, it's just a proposed new feature. In Bitcoin Core this would be much more complicated, but since CT needs explicit fees anyway, it is pretty simple to do it here.

**Comment by jtimon** [comment]
squashed for clarity

**Comment by jtimon** [comment]
A more correct version (with corrections after writting the tests) is in https://github.com/ElementsProject/elements/pull/185 for 0.14 instead of 0.13. Closing this one.

**Pull request closed without merging**
