### PR TITLE
fuzz: backport fixes to fuzzer errors

### PR DESCRIPTION
**Pull request by apoelstra**
Backport of https://github.com/bitcoin/bitcoin/pull/22279 and https://github.com/bitcoin/bitcoin/pull/22002 and https://github.com/bitcoin/bitcoin/pull/22137

### CODE REVIEW

**Comment by apoelstra** [comment]
Our CI uses Bitcoin's fuzzer corpus, meaning that when they add test vectors to it that they've fixed, our CI breaks until we fix them too :).

**Comment by apoelstra** [comment]
For some reason I needed to edit Marco's last commit with 
```
diff --git a/src/test/util_tests.cpp b/src/test/util_tests.cpp
index ec996dbe7f6..c7bb028b111 100644
--- a/src/test/util_tests.cpp
+++ b/src/test/util_tests.cpp
@@ -323,7 +323,7 @@ struct NoIncludeConfTest {
     {
         TestArgsManager test;
         test.SetupArgs({{"-includeconf", ArgsManager::ALLOW_ANY}});
-        std::array argv{"ignored", arg};
+        std::array<const char*, 2> argv{"ignored", arg};
         std::string error;
         (void)test.ParseParameters(argv.size(), argv.data(), error);
         return error;
```
to avoid compiler errors "missing template arguments before `argv`". I don't know why this is needed here but not upstream.

**Comment by gwillen** [comment]
Driveby quick review: utACK.

The `std::array` template thing appears to be a C++14 vs C++17 change. Is upstream on 17? Are we on 14 and should switch to 17?

**Review by jonasnick — COMMENTED** [review]
Not familiar with area of the code, but I can confirm that these are backports

utACK 0896d0a278c2e03cba8e9def912725387538650e

**Comment by apoelstra** [comment]
@gwillen if upstream has switched to 17, it was between 0.21 and 22.0 and we'll follow them as part of the 22.0 rebase.

**Comment by gwillen** [comment]
> @gwillen if upstream has switched to 17, it was between 0.21 and 22.0 and we'll follow them as part of the 22.0 rebase.

Oh, right, and that makes perfect sense because this is a backport. 👍

**Pull request merged**
