### PR TITLE
Disallow extended encoding for non-witness transactions

### PR DESCRIPTION
**Pull request by apoelstra**
Backport from upstream https://github.com/bitcoin/bitcoin/pull/14039

### CODE REVIEW

**Comment by instagibbs** [comment]
Apparently fails functional tests upstream, please tag the commit as an ustream fix: https://github.com/bitcoin/bitcoin/pull/14039

**Comment by instagibbs** [comment]
ok that might be an upstream problem only

**Comment by jtimon** [comment]
Should we move forward with this or close it?

**Comment by instagibbs** [comment]
it's not super urgent, let's just wait

**Comment by instagibbs** [comment]
tested and merged version in master, merging.

**Pull request merged**
